### ISSUE TITLE
Add enrollments as another tab in Profile

### ISSUE THREAD

**Issue by pbteja1998** [coderplex/learnplex#10]
Right now, to navigate to enrollments, you have to click on Profile > Enrollments.

<img width="338" alt="Screenshot 2020-05-11 at 8 08 31 AM" src="https://user-images.githubusercontent.com/17903466/81519366-9ee15d80-935e-11ea-9e95-2c1121f49427.png">

Remove Profile as a SubMenu and make it a single Menu Item, when clicked on profile, it should show the below page directly, and add Enrollments as a separate tab in this page.
<img width="1025" alt="Screenshot 2020-05-11 at 8 09 04 AM" src="https://user-images.githubusercontent.com/17903466/81519387-b28cc400-935e-11ea-90b0-c1e97405b666.png">

Right now, the above page is at /profile/settings, change it to /profile and show both Settings and Enrollments there itself.

**Comment by sridhar02** [comment]
i have fixed it ,gone rise a PR or this issue

**Comment by pbteja1998** [comment]
Resolved with #54
