### ISSUE TITLE
Cursor should automatically be in the title input inside New Section Dialog Box

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#107]
When a user clicks on the + button to create a new page, they see the dialog box. They have to manually click their mouse inside the input box for title to start typing. The cursor should automatically be there when they open the box 

Image : 
![image](https://user-images.githubusercontent.com/6577624/82608876-13c35b80-9bd9-11ea-9b92-0f0f7bcc1b2f.png)

**Comment by duttakapil** [comment]
Similarly, the cursor should jump inside the Content box when they click on the "Add Content" button 

Image : 
![image](https://user-images.githubusercontent.com/6577624/82609042-6270f580-9bd9-11ea-8a6f-924d65c2a13a.png)

**Comment by pbteja1998** [comment]
Fixed in #122
