### ISSUE TITLE
Reload after 'Delete' should open the page in the same state

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#108]
When user Deletes any page from the Index Page, the site reloads but the user doesn't find themselves in the same state. The sections are collapsed, and they have to open them again to continue editing 

After reload (ideally it shouldn't have to reload), the user should find themselves in the same section, page, as they were before clicking delete. 

GIF :
![delete-reload-collapse-sections](https://user-images.githubusercontent.com/6577624/82610524-2e4b0400-9bdc-11ea-9cba-c5a94955848a.gif)

Note : 
On relaod, the user also sees the 401 - Authentication error

**Comment by pbteja1998** [comment]
This is fixed
