### ISSUE TITLE
Allow user to type in topic, instead of just selecting 

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#112]
Right now, when creating a new resource, user has to select a topic from the drop down menu. Instead, they should be able to type their topic, and the dropdown should act as search results for every key. They can type the entire topic, and if it matches with a pre-existing topic name, they can move on, or they can select the topic from the list as they type it as well

Image : 
![image](https://user-images.githubusercontent.com/6577624/82666998-9fc69900-9c54-11ea-88fa-42f771ef0ff7.png)

**Comment by pbteja1998** [comment]
Refer to [Select with Search Field](https://ant.design/components/select/#components-select-demo-search).
