### ISSUE TITLE
Title of resource should be slightly bigger, bolder

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#114]
The title of the resource on the "cards" on the homepage stand out very little from the description underneath them. They are only slightly more bold. They should look bigger

Image :
![image](https://user-images.githubusercontent.com/6577624/82701492-eb496900-9c8d-11ea-9c01-753bb173d663.png)

**Comment by sb255** [comment]
@pbteja1998 Can I work on this?

**Comment by pbteja1998** [comment]
@sb255 sure, go ahead. I will assign this to you. 

Checkout `Typography.Title` component for this.

**Comment by sb255** [comment]
Okay, sure

**Comment by pbteja1998** [comment]
This is fixed now
