### ISSUE TITLE
Use a library of default images for resource thumbnails 

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#147]
At the moment, we only show text throughout our site. We do not have any images. We should at least be showing them thumbnails for the resources. We can select a set number of topics, for example : 
- Data Structures and Algorithms 
- Computer Science 
- React 
- Angular 
- Vue 
- HTML
- CSS
- JavaScript
etc..

And select one Creative Commons licensed image from the Internet for each of the topics. When user selects the topic, it can automatically use that image as the thumbnail. We can later expand to more images, and perhaps even allow the user to upload their custom image. 

The images should be as unopinionated as possible.

**Comment by TheDheeraj007** [comment]
Hi @duttakapil 
I'm working on this issue. Can you assign it to me?

**Comment by duttakapil** [comment]
@TheDheeraj007 make sure the share the images here with us before you add them to the resources / site locally. We should have a discussion on what images we should use

**Comment by TheDheeraj007** [comment]
Hi Kapil, 
Bhanu and I have decided to have a default image for those topics we don't have a logo of. 
So for that, I'll be using the CoderPlex logo image as the default image. (Let me know if you have a better idea)

So far, I'm using the following images for topics:
![java](https://user-images.githubusercontent.com/17236629/83531054-1b083480-a50a-11ea-95c0-90ced15f3ed8.png)
![angular](https://user-images.githubusercontent.com/17236629/83531584-ce712900-a50a-11ea-95ea-06748dbf9195.png)
![react](https://user-images.githubusercontent.com/17236629/83531592-d16c1980-a50a-11ea-967d-fa95f7e48e5c.png)
![vue](https://user-images.githubusercontent.com/17236629/83531595-d3ce7380-a50a-11ea-95bf-a75d67d0594d.png)
![python](https://user-images.githubusercontent.com/17236629/83531602-d5983700-a50a-11ea-9229-43ff65560cd0.png)
![html](https://user-images.githubusercontent.com/17236629/83531621-dc26ae80-a50a-11ea-8aac-e3bbbbc5cd78.png)

**Comment by TheDheeraj007** [comment]
This one for javascript
![image](https://user-images.githubusercontent.com/17236629/83533638-7556c480-a50d-11ea-8729-ff8e65fb1c90.png)

**Comment by TheDheeraj007** [comment]
![image](https://user-images.githubusercontent.com/17236629/83534067-ff069200-a50d-11ea-8061-de445844cbc4.png)

**Comment by duttakapil** [comment]
These seem fine to me. But we should reduce the size of the logo, to fit inside the box better. It shouldn't take the entire height of the tumbnail

**Comment by TheDheeraj007** [comment]
Okay! I'll do that and add the screenshot here.

**Comment by vinaypuppal** [comment]
@TheDheeraj007 We used these https://konpa.github.io/devicon/ in https://coderplex.org site and these are font icons. But there is a react package for this using which you can import only what you need https://fpoumian.github.io/react-devicon/ Please use this instead.

**Comment by TheDheeraj007** [comment]
@vinaypuppal So we don't need to download these images locally and we can use them by referencing these remote images

**Comment by TheDheeraj007** [comment]
Hi @vinaypuppal 
Do you know about the following issue:
I installed the required package using  yarn add 'react-devicon' 
Afer that when I'm trying to put following example import:
import IconAmazonwebservices from 'react-devicon/amazonwebservices/original'
I'm getting the following compilation error:

_Could not find a declaration file for module 'react-devicon/amazonwebservices/original'. '/Users/learnplex/node_modules/react-devicon/amazonwebservices/original/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-devicon` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-devicon/amazonwebservices/original';_

Here it is asking to run `npm install @types/react-devicon`. Is there any corresponding yarn command? Or any other workaround?

**Comment by duttakapil** [comment]
I like the Devicon images @vinaypuppal shared above. Also observe the size of the icons in the thumbnails on [coderplex.org/learn](https://coderplex.org/learn/) page, they are smaller and have more space inside. We need to stick to that.

![image](https://user-images.githubusercontent.com/6577624/83704174-f8bc0700-a62e-11ea-9fde-e4419b9f9bab.png)

**Comment by duttakapil** [comment]
There will be lots of resources that do not fall into the catagory of individual technologies. We will need to create unique images for this purpose. 

This is what Codecademy is using, for example. 
![image](https://user-images.githubusercontent.com/6577624/83704325-7253f500-a62f-11ea-968b-907895ce81eb.png)

We could provide the user with some webpage on our site where they can submit new images for this purpose, and give it tags. Once accepted by us, any of the users can use any of these images for their resource thumbnails

**Comment by pbteja1998** [comment]
> Hi @vinaypuppal
> Do you know about the following issue:
> I installed the required package using yarn add 'react-devicon'
> Afer that when I'm trying to put following example import:
> import IconAmazonwebservices from 'react-devicon/amazonwebservices/original'
> I'm getting the following compilation error:
> 
> _Could not find a declaration file for module 'react-devicon/amazonwebservices/original'. '/Users/learnplex/node_modules/react-devicon/amazonwebservices/original/index.js' implicitly has an 'any' type. Try `npm install @types/react-devicon` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-devicon/amazonwebservices/original';_
> 
> Here it is asking to run `npm install @types/react-devicon`. Is there any corresponding yarn command? Or any other workaround?

@TheDheeraj007 
I don't think types exist for `react-devicon`. Try `yarn add -D @types/react-devicon`. If it doesn't work, then add the line`declare module 'react-devicon'` in `src/types/index.d.ts`. We will add our own types later.
