### ISSUE TITLE
Fix alignment of title and description

### ISSUE THREAD

**Issue by pbteja1998** [coderplex/learnplex#15]
The `Edit Section Title` form item is not aligned properly with the below editor in `edit mode` of page. Fix that so that they both properly align with each other.

<img width="997" alt="Screenshot 2020-05-11 at 8 36 27 AM" src="https://user-images.githubusercontent.com/17903466/81520658-8d01b980-9362-11ea-90e7-34a10968e4d2.png">

Also, the form items for editing title and description of a page are not properly aligned with the below Resource Index. Fix those.
<img width="997" alt="Screenshot 2020-05-11 at 8 38 44 AM" src="https://user-images.githubusercontent.com/17903466/81520785-dc47ea00-9362-11ea-85f7-99bb5545a569.png">
<img width="997" alt="Screenshot 2020-05-11 at 8 38 50 AM" src="https://user-images.githubusercontent.com/17903466/81520795-e10c9e00-9362-11ea-9d69-e44cb6880e02.png">

**Comment by m-code12** [comment]
I would like to work on this issue.Please assign me @pbteja1998 .I can resolve it using bootstrap classes.

**Comment by pbteja1998** [comment]
> I would like to work on this issue.Please assign me @pbteja1998 .

@srinivaspavan9 has already started working on it.

**Comment by srinivaspavan9** [comment]
> > I would like to work on this issue.Please assign me @pbteja1998 .
> 
> 
> 
> @srinivaspavan9 has already started working on it. 

Done with it working on new issue. If you like any changes I can do it.
