### ISSUE TITLE
[Critical Bug] Pages do not open in edit mode, redirects to Index page

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#168]
Seems like, sometimes when creating or opening a page, it doesn't open. This started happening a few days ago. I added content, and created the page, and wasn't able to open it. When you go to the URL directly, it is empty. 

This seems to happen for some time only. Not sure what are the conditions under which this happens.

GIF:
![page-does-not-open](https://user-images.githubusercontent.com/6577624/83710480-79ceca80-a63e-11ea-9d3b-0e0404116e50.gif)

In the above GIF, I had just created the Week 7 and Week 8 sections. I added the content from the Create Page dialog box. I was expericing this a few days ago when I created the Week 6 Section pages. I gave up doing anything, because it couldn't edit the page. Now I was able to edit the Week 6 page, and moved on to created 7 and 8, and noticed this same issue. 

I am currently able to navigate to the Week 7 and 8 pages.

**Comment by pbteja1998** [comment]
Fixed in https://github.com/coderplex/learnplex-backend/commit/0dee3fc9f6ac2c2df2ef61a1e277b9cffba242c0
