### ISSUE TITLE
Meta data isn't not loading when sharing URL of resources

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#173]
When sharing any resource or page URL on any social media platform, the metadata of the page i.e. the title, description, of that page should be loaded with the link and shared. This isn't loading right now. It's only showing "Coderplex" name, instead of the resource or page title. 

I have tried changing the link by adding some keys after `?` at the end of the URL, doesn't seem to matter.

Example : 
![image](https://user-images.githubusercontent.com/6577624/83855702-17f18c00-a736-11ea-8fab-9e044e8054eb.png)

**Comment by pbteja1998** [comment]
Fixed in https://github.com/coderplex/learnplex/commit/7c44158978442823b48a6dd3d4c1f39a83ca1ae8
