### ISSUE TITLE
Site redirects to View Mode when you click on any sidebar item, even in Edit Mode

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#29]
The sidebar items seems to redirect to only the view mode version of the pages. When editing any page, if you click on any of the items in the sidebar to navigate to a different page, the site redirects you to the view mode. 

And it also doesn't show the Edit or Exit button on the top anymore, since it is in Edit mode technically, but also in View Mode

**Comment by pbteja1998** [comment]
Fixed
