### ISSUE TITLE
Items on Index Page don't seem to be clickable 

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#30]
**Describe the bug**
When clicking on any of the items in the Index Page, they do not do not seem to do anything. They don't seem to be clickable anymore.

**To Reproduce**
1. Go to 'https://coderplex.in/learn/learn-data-structures-and-algorithms-:-foundation'
2. Click on 'Getting Started' or "Basic Math Operations" or open any section and click on any page
3. See error

**Expected behavior**
It should open the respective page

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [76.0.1]

**Comment by pbteja1998** [comment]
Fixed

**Comment by duttakapil** [comment]
This bug seems to be back. Unable to open the pages with one click. Have to click multiple times to open
