### ISSUE TITLE
Sidebar doesn't show the correct format for title of the section

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#34]
We recently updated the sidebar to only show the pages of the current section. But now, the sidebar doesn't seem to show the title of the Section that the user is inside, which can make their learning experience a bit confusing. 

If we could show the super-section and current section above the list of pages, below "Index" that would be helpful 

We can show it in the folder format perhaps
Eg : `super-section > current-section`

**Comment by pbteja1998** [comment]
Fixed

**Comment by duttakapil** [comment]
Section heading should show the `grandparent section/parent section`, instead of `parent section / page`

Current :
![image](https://user-images.githubusercontent.com/6577624/82027742-54d7df00-96b2-11ea-8d84-e9be945adbb7.png)

Should be : `Asymptotic Analysis (Big O Notation) / Basics`

Page : https://coderplex.in/learn/learn-data-structures-and-algorithms-:-foundation/asymptotic-analysis-(big-o-notation)/basics/the-basics-of-big-o-notation
