### ISSUE TITLE
Change YouTube Embed Shortcut to Ctrl + Y for Windows

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#39]
Right now, the keybaord shortcut for embeding a YouTube link is Shift + Y. But when editing content normally, the user might need to use capital Y, and would need to use Shift + Y for it, but this automatically creates the markdown text for the YouTube embed 

Because of this, we should change the command to Ctrl + Y ideally or some other letter

**Comment by krushiraj** [comment]
Is this just issue just for Windows? I mean is shift+Y shortcut specific to Windows OS?

**Comment by duttakapil** [comment]
I am not sure what the shortcut is for Mac. @pbteja1998 ?

**Comment by pbteja1998** [comment]
@krushiraj No, the editor I am using doesn't come with shortcuts. I added the shortcuts. Right now, the shortcut is set to Shift+Y, we need to change it to Ctrl + (Some other letter). Since ctrl+y is for redo

**Comment by pbteja1998** [comment]
We need to add ctrl + (letter) and also meta + (letter) for shortcut

**Comment by pbteja1998** [comment]
@krushiraj [Refer this file](https://github.com/coderplex/learnplex/blob/master/src/components/learn/Editor/CustomKeyboardEventHandler.tsx)

**Comment by krushiraj** [comment]
How about cmd/ctrl+shift+y ? Seems like it is not bound to any of our shortcuts and system specific shortcuts (https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts)

**Comment by duttakapil** [comment]
I like that. Because Ctrl + Y is for redo, if I am not wrong. Ctrl + Shift + Y should be fine I think

**Comment by pbteja1998** [comment]
So, the shortcut would be ctrl+sift+y and meta+shift+y
