### ISSUE TITLE
Remove sidebar on Index Page in View Mode

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#46]
Right now, we are showing the sidebar on the Index Page. This doesn't make sense to do this in view mode, since the user is already seeing the entire Index on the right. So we can remove the sidebar on the Index Page

We shouldn't however remove it from the Index Page in Edit Mode, because while editing a resource, the creator might need to navigate to any of the pages and edit the content there, and the sidebar would help with that. In edit mode, Index Pages transforms into Edit Index page

Eg resource : https://coderplex.in/coderplex/learn/edit/learn-data-structures-and-algorithms-:-foundation/resource-index

**Comment by pbteja1998** [comment]
fixed
