### ISSUE TITLE
Website performance is very poor, resources take upto 5-10 secs to load

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#72]
The website performance right now is very poor. It takes between 5-10 secs to load a resource and to also move between pages 

Eg Resource : https://coderplex.in/learn/learn-data-structures-and-algorithms-:-foundation

GIF
![perfromance-issue](https://user-images.githubusercontent.com/6577624/82030151-aa61bb00-96b5-11ea-906d-16cad744dfdd.gif)

**Comment by pbteja1998** [comment]
Now, it should not take that much time to move between pages, but it still is taking time to move from index to a page or vice-versa.

**Comment by duttakapil** [comment]
Opening the [Index Page](https://dev.coderplex.org/) also takes a lot of time still

**Comment by duttakapil** [comment]
Now we have a new problem, it's taking forever to load the titles of the sections on the Index Page when you expand them. Moreover, if you collapse them and expand them again, they seem to load again. This is very bad 

GIF 
![loading-section-titles-in-index-performance](https://user-images.githubusercontent.com/6577624/82073710-3ea04200-96f7-11ea-8223-dabcd9e0ee60.gif)

**Comment by pbteja1998** [comment]
Fixed.
