### ISSUE TITLE
Logo and Coderplex name are not correctly aligned with each other

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#73]
![image](https://user-images.githubusercontent.com/6577624/82030367-00366300-96b6-11ea-9c88-6bfbb3ee6a8e.png)

**Comment by aravindballa** [comment]
Is this still an issue? Looks good on https://coderplex.in

**Comment by pbteja1998** [comment]
@aravindballa  Yeah, they are aligned properly now. But I am unable to reduce the size of logo.

**Comment by aravindballa** [comment]
I reduced it a bit in #83

If you have any specific size in `px`, comment on that PR and I can make that change.

**Comment by pbteja1998** [comment]
No, it's fine. If we are able to reduce it, then i can change it later too, when needed. I was unable to do so before without breaking things.

**Comment by pbteja1998** [comment]
Fixed in #83
