### ISSUE TITLE
Opening Index page gives 404 error for a second 

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#8]
When you click on "Edit Index" button on any resource, it gives a 404 error for a couple of seconds, before redirecting to the Edit Index page

**Edit**: It is showing `401` page - not `404`.

**Comment by duttakapil** [comment]
Gif 

![404 on opening index page](https://user-images.githubusercontent.com/6577624/81786301-15c45500-951d-11ea-9d9f-76c88edbb0cc.gif)

**Comment by duttakapil** [comment]
GIF 2 

![index-page-404-error](https://user-images.githubusercontent.com/6577624/81864626-8786b800-958a-11ea-9049-10ec58a690ee.gif)

**Comment by pbteja1998** [comment]
Fixed
