### ISSUE TITLE
Fix logo rendering in safari browsers

### ISSUE THREAD

**Issue by pbteja1998** [coderplex/learnplex#89]
<img width="1046" alt="Screenshot 2020-05-19 at 8 40 12 AM" src="https://user-images.githubusercontent.com/17903466/82280384-6835c380-99ac-11ea-9fc1-739f90d9585a.png">
<img width="298" alt="Screenshot 2020-05-19 at 8 41 28 AM" src="https://user-images.githubusercontent.com/17903466/82280461-8c91a000-99ac-11ea-80c4-40d657551490.png">

In safari browsers, both in mobile and desktop, logo is not rendering properly.

**Comment by pbteja1998** [comment]
@duttakapil when was the image in #115 taken?

**Comment by duttakapil** [comment]
I didn't see that this was fixed. Seems like it is

**Comment by pbteja1998** [comment]
OK, closing this then.
