### ISSUE TITLE
Complete button is not reflecting changes until page is rerendered

### ISSUE THREAD

**Issue by krushiraj** [coderplex/learnplex#9]
**Describe the bug**
When I click on complete button after finishing a topic it is not getting reflected the first time until there is a rerender of page or reload. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a resource say `https://coderplex.in/aravindballa-coderplex/learn/gatsby/intro`
2. Click on any of the sections say 'Intro'
3. Click on Complete to mark it complete
4. It is not turning to green until I reload/click on next/prev

**Expected behaviour**
The button should turn to green and say completed without any re render required

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.4
 - Edge, Chrome, Firefox

**Smartphone (please complete the following information):**
Not tested on smartphone

**Comment by pbteja1998** [comment]
This is fixed.
